### PR TITLE
New Node/Express Web Interface

### PR DESCRIPTION
**Pull request by 722C**
This is an initial framework for a web interface.  This begins to deal with #27 and part of both #25 and #26.

The framework is based off of a simple Express server located in `/WebApplication/index.js`.  If you hit the server at `/`, `static/index.html` will be served up.

The `index.html` uses both [http://riotjs.com](url) and [https://github.com/mzabriskie/axios](url) for creating the components and communicating with the server.  Ideally, we could eventually switch out axis with Socket.IO without much work or many changes.

`index.html` is split into two columns; the left is composed of `GET` commands, and the right is composed of  `POST` commands.  `POST` commands are currently set up to run on intervals with 1 second delays.  Clicking the associated button will toggle the interval on or off.

Currently the server is not calling any functions due to the fact that there are not any extant functions for it to call, though it should be easy to modify the endpoints of the server to add these in.  Additionally, it should be pretty easy to add or remove both endpoints and individual components of the web interface.

### CODE REVIEW

**Comment by nfcopier** [comment]
I'm going to go to the lab and run some manual tests on this on the Beaglebone sometime soonish.
Overall, this looks pretty good.

A couple things to note:
DiveMaster uses an outdated interface and it is not necessary to implement those functions.
IThruster is an interface between the C++ and the hardware and it is not necessary to implement that interface in the Node app.

**Comment by nfcopier** [comment]
Also, I think it would be better to exclude the Node modules from Git and add them to the .gitignore. Instead, add the packages.json to Git and install the modules as part of the build process.
That might just be a personal preference, though. So I'll leave it up to your discretion.

**Comment by 722C** [comment]
I agree with you in regards to the `node_modules`, but it was included previously and I am unsure as to how we would add the installation into the build process.  Currently, the only packages that I manually installed (i.e. not installed through another package's `package.json`) are in our `package.json`.

**Comment by nfcopier** [comment]
I would add a shell script for it in the Scripts folder.

**Comment by nfcopier** [comment]
I got the error `Cannot find module 'debug'` in node_modules/finalhandler/index.js:14:13 when try to start index.js.
Am I missing a dependency?

**Comment by 722C** [comment]
What version of node are you running?

**Comment by 722C** [comment]
Hmm...

It looks like `body-parser` didn't automatically install that into it.

Run a `npm install` and you should be good.

**Comment by nfcopier** [comment]
I'll try that when I get back to the lab. Thanks.

**Comment by kburgon** [comment]
I got it to work on my computer, so we're good to go!

**Pull request merged**
