### PR TITLE
Added clear buffer

### LINKED ISSUE #132: Arduino Reads Garbage On Initial Startup
## Summary

When the Arduino's Serial is connected to for the first time, garbage data is given via `Serial.read()`.
What I discovered is that most times, the 'value' of the garbage is consistent but the amount of garbage is random. The value of the garbage is unique to both the baud rate and the Arduino device. For the Arduino Due with a baud of 115200, the garbage value is '0'.

Note: `Arduino.available()` will not resolve this issue.
## Acceptance Criteria

When the Arduino is initialized, it
- [ ] cycles through the input buffer until the buffer is clear
- [ ] sends a response of `"ready"` to the BeagleBone
- [ ] catches any exceptions and returns "`failure`" to the BeagleBone
## Non-functional Criteria

The `"ready"` response is valid JSON. An extra JSON library doesn't needed to be added to finish this issue.

### PR DESCRIPTION
**Pull request by emersonudy**
Hey can you look at this. Hopefully I did the pull request right. @nfcopier 

Fixes #132.

### CODE REVIEW

**Comment by nfcopier** [comment]
As a matter of style, I suggest having the preprocessors at the top of the file. Something like:
```C++
#ifdef UNO
#define GARBAGE_VALUE 240
#else
#define GARBAGE_VALUE 0
#endif
```
And later in file:
```C++
if(Serial.read() != GARBAGE_VALUE)
```
This allows you to keep all of the preprocessors together.

**Comment by nfcopier** [comment]
It has been suggested that `while(!Serial)` will do the same job.

**Comment by emersonudy** [comment]
I added the changes.

**Comment by nfcopier** [comment]
I think it would be a good idea to have @TekuConcept test this on the sub and verify it works, just to be sure. But this looks good to me.

**Comment by TekuConcept** [comment]
Code Works!

**Comment by TekuConcept** [comment]
Oops

**Pull request merged**
