### PR TITLE
Kill Switch Integration

### PR DESCRIPTION
**Pull request by TekuConcept**
The kill switch controller has been added. ThrustController has been patched to allow an offset, taking into account imperfections in ESCs' hardware.
The new controller utilizes interrupts to disable the thrusters in real-time.

### CODE REVIEW

**Comment by nfcopier** [comment]
Why was the temperature/pressure sensor stuff added to this branch?

**Comment by TekuConcept** [comment]
This branch should be called "Arduino Features" but when I created it, I felt like it was going to be merged right then and there. Really I didn't want to create a separate branch and run into merger conflicts - like what happened in the past.

**Comment by TekuConcept** [comment]
The kill switch works!

There really wasn't any changes that needed to be made to the code, but to the hardware its self.
(First, there were no pull-ups so the switch was 'floating' when open, meaning unpredictable results. Second, one of our engineers accidentally miswired the connector such that the kill switch was never part of the circuit to begin with.)

**Comment by nfcopier** [comment]
:+1:

**Comment by nfcopier** [comment]
Awesome. We just need to get it up to date with develop now.

**Pull request merged**
