### PR TITLE
Adds New Hardware Drivers For Hydrophones

### PR DESCRIPTION
**Pull request by TekuConcept**
The core functionality follows these steps:
1. Listen for a sound that exceeds a threshold amplitude.
2. Fill buffers and sort.
3. Process buffer data and sort out time differences.

### CODE REVIEW

**Comment by nfcopier** [comment]
I just have a couple thoughts on this:

As you probably expected, I do find the code a little messy and hard to read. But overall, it's not terrible. And I'm sure some of it had to be done to make the code run efficiently enough. I do think there is some cleanup that we should do together. But considering the complexity of this algorithm and the difficulty in optimizing code, I don't think it's worth taking the time before competition. Maybe sometime in the next semester.

I'd like you to tweak the format the data is returned to be valid JSON. This will make it easier for BoneCentral to parse. Correct me if I'm mistaken, but it looks like you set the HydroController to return three time values corresponding to each of the hydrophones, which BoneCentral will be able to use to triangulate. So the returned JSON should be something like:
```
{
  "Left": time0, // Or whichever time would correspond to Left
  "Right": time1,
  "Front": time2
}
```
More compactly:
```
{ "Left":time0,"Right":time1,"Front":time2}
```
If it turns out not to be efficient enough to send that through the Serial port, we could just do a JSON array:
```
[time0,time1,time2]
```
But for clarity, I'd prefer the object.

Lastly, it appears you have not yet added an instance of HydroController to the controller array.

I'm going to add an instance of HydroController to the array as a local change so I can test this. And I'll merge if it passes. Afterwards, I'd like you to update the controller array and JSON on a second branch, if you wouldn't mind.

**Comment by TekuConcept** [comment]
Great idea with JSON formatting. I know I saw it somewhere but couldn't put a name on it so I just created something similar from memory.

Also thanks for the heads up! I completely forgot to add that little bit.

**Comment by nfcopier** [comment]
Actually, rethink this, I think the JSON object should have a property `State` which is equal to `activated`, `busy`, or `ready`.
```
{"State":"ready","Left":time0,"Right":time1,"Front":time2}
```
```JSON
{"State":"activated","Left":null,"Right":null,"Front":null}
```
```JSON
{"State":"busy","Left":null,"Right":null,"Front":null}
```

**Comment by nfcopier** [comment]
@TekuConcept, I think we need to meet and and finish this work.

**Pull request closed without merging**
